### ISSUE TITLE
请问如何修改组件的长高比例

### ISSUE THREAD

**Issue by WangPengcheng** [waynecz/vue-img-inputer#28]
修改成竖向图片

**Comment by waynecz** [comment]
可以通过修改`.img-inputer`的样式达到目的

```css
.img-inputer {
   width: 100px;
   height: 400px;
}

```

到那会有些组件内其他元件的位置问题，也需要修改 css 来兼容
